version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/prod_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
  web:
    build: .
    command:  /bin/bash -c 'while !</dev/tcp/db/5432; do sleep 1; done && python3 source/app.py'
    volumes:
      - .:/home/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    ports:
      - "8081:8081"
    depends_on:
      - db
